### ISSUE TITLE
Is it possible to use this library without exceptions and rtti?

### ISSUE THREAD

**Issue by phillipjohnston** [rollbear/trompeloeil#101]
Hi, 

I'm developing an embedded C++ framework, and notably exceptions are kept disabled by default (at least in the current incarnation).

Is this library usable in such an environment?

**Comment by phillipjohnston** [comment]
I'll add RTTI to my inquiry.

(One path I'm considering it isolating the mocking to host-only code, which could utilize RTTI and exceptions but I'd prefer to use the same flags for testing and deployment if I can get away with it)

**Comment by rollbear** [comment]
Away at the NDC{Techtown} conference right now, so I'll be a bit inattentive for a few days, but please fill in more info about your SW and your test environment, so that I can come back with a response later.

**Comment by phillipjohnston** [comment]
Hope you're enjoying the conference!

I'm currently developing the framework on OSX using clang & gcc . I'm using doctest 1.2.9 as the unit testing framework, and interested in trompeloeil for mocking support.

I am building libcxxabi and libcpp locally and linking them with my embedded/simulator applications. Unit tests will primarily run on the host machine, which does not have a hard no-exceptions/no-rtti requirement.

Forgive the sparse details here, I'm not sure exactly what is relevant :). I'm in the early implementation stages, so things are still quite squishy and amorphous.

**Comment by rollbear** [comment]
OK, **Trompeloeil** itself does not throw exceptions, but it defaults to it when reporting violations. It *does* use RTTI for one thing, and that is when you use `deathwatch<T>`,and an object is unexpectedly destroyed.

The easiest way forward is definitely to build unit tests on and for the host machine, with both RTTI and exceptions supported, even for the unit under test.

2nd easiest is to build your unit under test on and for the host machine, but without RTTI and exceptions, but allow both RTTI and exceptions for the unit test program itself. For this I think you'd need to write a reporter function that reports errors without throwing. This is a bit cumbersome, because there are errors that when detected, must not return (for example call to a mocked function that has a return type, but no expectations. There is no way to know what value to return, so it mustn't return.) Without exceptions I believe your only chance is to terminate on those errors.

Building the test program also without RTTI should work, as long as you do not use `deathwatched<T>`in any test. I'm uncertain about building the test program without support for exceptions, but I believe this would be difficult. Unfortunately **Trompeloeil** has a few, actually completely unnecessary, try/catch blocks that were introduced to silence some warnings from MSVC.

Does this help?

**Comment by AndrewPaxie** [comment]
Catch2 v2.4.0 has been released which has experimental support for `-fno-exceptions`.
<https://github.com/catchorg/Catch2/releases>

Their implementation chooses to call `std::terminate()` by default where an exception would
otherwise be thrown, but they document a customization function which provides a hook
to change this behaviour.
See: <https://github.com/catchorg/Catch2/blob/v2.4.0/docs/configuration.md#disabling-exceptions>

**Comment by phillipjohnston** [comment]
@AndrewPaxie thank you for letting me know, looks like Catch will be my test framework of choice for this project.

@rollbear I really appreciate the detailed feedback and context for RTTI, it is quite helpful.
