### ISSUE TITLE
Allow pointer-to-mock semantics in assertion macros

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#103]
Right now, `REQUIRE_CALL` and other macros that require the mock instance to be provided require non-pointer types. However, it would be useful if I could pass in pointer-like objects, such as:

* `T*`
* `std::unique_ptr<T>`
* `std::shared_ptr<T>`

Example:

```
auto mockInterface = std::make_unique<SomeMockClass>();
REQUIRE_CALL(mockInterface, DoStuff(_))
```

**Comment by rollbear** [comment]
This is true, but how important is it, given that `REQUIRE_CALL(*mockInterface, DoStuf(...))` works for all the above?

**Comment by rcdailey** [comment]
It's an arguably unnecessary syntactical distinction when I refactor my unit tests to interchangeably use non-pointer types and pointer types. I now have to update each call site to dereference or not-dereference. I think with some template specialization trickery, you could make this more agnostic. I'll toy around with something and submit a PR.

**Comment by rollbear** [comment]
I don't expect it to be difficult to implement, but it'll come at a cost of  longer compilation time for all expectations. I'm not convinced that this is beneficial. Short compilation times are important for unit tests.
If you can show that it's (more or less) for free, than I'm in favour.

**Comment by rcdailey** [comment]
Do you have any ideas on how to best accomplish this from an implementation
standpoint? I tried a few things, such as partial template specialization
of a class to ambiguously hold pointer and non-pointer types, with an
overloaded `->` operator, but this proved difficult to use.

To your compile time argument, I don't think there would be any meaningful
or significant impact. If it's 1 extra template class I don't see the
issue. Do you have any evidence to back up your claim? Perhaps a specific
implementation in mind that brings concern?

**Comment by rollbear** [comment]
I admit I have not given it much thought.

My basic idea is that you need to pick apart the implementation of the `TROMPELOEIL_REQUIRE_CALL_OBJ` macro. In there is the `call_validator_t`, which needs to do some clever `SFINAE` to figure out if `obj` or `*obj` is the thing. That needs to propagate back, so that the rest of the macro uses the result.

There's also the matter of how to handle someone writing tests involving a custom smart pointer type, where you'd have to make the right choice between a matching call to, say `ptr.get()` and `(*ptr).get()` (for some `my_smart_ptr<T> my_ptr...`, which may not be very obvious at all, especially if both are valid calls.

As for the compile time argument: few things in C++ have a higher compile time cost than `SFINAE`, and I don't see how you can do this without.

https://www.reddit.com/r/cpp/comments/6gur2x/the_rule_of_chiel_aka_compiletime_cost_of/

**Comment by rcdailey** [comment]
Interesting, I never really analyzed the compile time cost of certain metaprogramming techniques. I guess SFINAE is so useful that generally it outweighs the cost of compilation time. I wonder what the real-world, overall and noticeable compile time impact SFINAE has. I guess it depends on how pervasive your header files are.

In any case, I believe `constexpr if` would allow the same flexibility with a fraction of the cost. It requires C++17, though. Is that something you're willing to allow?

If you are wary to enforce a minimum, we could use some preprocessor conditions checking `__cplusplus` and make these semantics opt-in depending on available language features (basically, if someone is using C++17, they would be able to pass in pointers via `obj` and `*obj` (the latter for backward compatibility). Ultimately this is a decision between cost of complexity and enforced minimum language iteration.

And at a 10,000ft level, I realize this isn't that important of a change. We're talking about saving a `*` basically. It's important to me, but maybe no one else. I find it annoying to refactor unit tests and have to change hundreds of lines of code to use `*obj` instead of `obj` when I go from non-pointer to pointer type (usually due to having introduced new ways of doing dependency injection in legacy code to make it testable; usually requiring the introduction of smart pointers for resource management). If you feel, objectively, that the cost of introducing this functionality outweighs its usefulness to your general audience, then I think that would be a fair assessment and I would agree to just put up with it.

Let me know! Thanks for your help.

**Comment by rollbear** [comment]
I honestly haven't done a deep analysis myself, but I've often made compilation time comparisons of different solutions to the same problem, and I strive for the shorter build time, even if it makes the implementation of the library messier. If you want some details, though, I can recommend a recording of a TMP conference talk by Odin Holmes:

https://www.youtube.com/watch?v=ZpVPexZHYrQ

I'm not gonna scrap C++14 support. I have considered offering additional functionality if built with C++17, but I don't think I've found a solution for that that is guaranteed not to mess things up for people upgrading compiler for their existing code base. Hopefully I will find a solution, because there are a few things I'd like to add.

When C++20 is out, I may create a new library instead, addressing some design mistakes that cannot be fixed without breaking existing code.

**Comment by rcdailey** [comment]
Going close this one out, as it's not super important and I don't have the time to do anything about it. Thanks for your involvement in discussion.
