### ISSUE TITLE
Ceci n'est pas un objet

### ISSUE THREAD

**Issue by PhDP** [rollbear/trompeloeil#11]
I love the reference to "Ceci n'est pas une pipe" in the readme, but "objet" is masculine (makes no sense but yeah, that's French), so it should be "Ceci n'est pas un objet". I don't want to be a grammar nazi, I hate French grammar, just thought you might want to know :P

Ref: https://en.wiktionary.org/wiki/objet

**Comment by rollbear** [comment]
Danm, and I even ran that past an ex colleague who is French. Oh, well. I'll fix it.

**Comment by francoisgenolini** [comment]
I did spot this but it did not offend me ;-)  I am used to hear British people attempt to talk to me in French, and I am glad enough that they make the effort, so I let these kind of mistakes go unchallenged.

If you wanted to keep the feminine ("une") you could write:
<< ceci n'est pas une chose>>
which actually would be much more informative, as it would literally and correctly illustrate the intention of the diagram:  a mocked object (the subject of the illustration is a UML object diagram of an instance of a Mock class) is not a "thing", but a straw man or proxy for one of the interfaces that the class might support.

Regards,

Francois

**Comment by rollbear** [comment]
Thanks. I have to think about that. On the one hand I love your version, and the explanation for it. On the other hand, "objet," is a word I expect programmers who don't know French at all (like me) still understand.

If I go with "ceci n'est pas une chose," may I quote you in the FAQ?

**Comment by francoisgenolini** [comment]
Hi,

Yes please do as you want.
This was not really a suggestion, just nick picking.
I did like “objet” as indeed it might look similar to the word “object”.
“Chose” is actually not an academically relevant word: my teachers always told me to think of an appropriate word instead of just calling everything a “thing”.  Good for colloquial exchanges, not appropriate for competent technical writing.

Kind Regards,

François Génolini
Head of Technology

POSITIONEERING Limited
Direct:      +44 1224 968 104
Mobile:     +44 7480 126 316
Email:       francois.genolini@positioneering.com<mailto:francois.genolini@positioneering.com>

Company Registered in Scotland No. SC347964

The information contained in this communication is confidential, is intended only for the use of the recipient named above, and may be legally privileged. If the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please resend this communication to the sender and delete the original message or any copy of it from your computer system.

**Comment by rollbear** [comment]
Fixed. No new release tag for this alone, but at least viewing the README.md, or the cheat sheet PDF on the main github page  looks OK now.

**Comment by rollbear** [comment]
Closing now with release v17.
