### ISSUE TITLE
Option to automatically sequence expectations

### ISSUE THREAD

**Issue by rcdailey** [rollbear/trompeloeil#120]
I would like the ability to specify that the appearance-order of expectations in the code defines the sequence in which they must be called. See the example below (the goal is to avoid an explicit `trompeloeil::sequence` definition and corresponding `.IN_SEQUENCE()` statements, which helps cut down on boilerplate code and makes the sequence easier to understand since the order is defined by the lines of code):

```cpp
{
    trompeloeil::implied_order_sequence seq;
    REQUIRE_CALL(mockObj, SomeFunction1()); // Automatically does `.IN_SEQUENCE(seq)`
    REQUIRE_CALL(mockObj, AnotherMethod()); // Also automatically does `.IN_SEQUENCE(seq)`
    mockObj.DoStuff(); // SomeFunction1() called first, AnotherMethod() called second
}
```

I'm sure with the macros, you can somehow automatically detect when a `implied_order_sequence` is defined and make it use that or something. Thoughts?

**Comment by rollbear** [comment]
No, this is a really bad idea, and one that google mock got spectacularly wrong.

It optimises for the wrong problem. It gives you a slight convenience when writing test code, at the cost of making it harder to read and reason about, due to hidden functionality. You *really* want test code to be easy to read.

**Comment by rcdailey** [comment]
Could you explain a little more about why this is a bad idea? In my mind, it's easier to read because the order of the sequence is also the order in which you read it in the code (top to bottom). Based on my example above, why would I ever want to have the code order different from the sequence order? And why do you argue that is easier to read than the alternative, where they both align?

I think it's OK to state that you disagree, but it would be more helpful if you explained, possibly with examples, and elaborate a lot more so I get a better understanding. This ultimately boils down to how you designed your library to be used, and I think it's a good idea to make that clear.

Thanks!

**Comment by rollbear** [comment]
It is a bad idea because it adds a completely hidden dependency. There is no visible code that says that behaviour changes. It happens when an object exists. With your 3 line example, it's not *that* bad, but things tend to grow. When the distance grows between defining the object, and the expectations that are affected by it, the hint that something happens becomes very vague.

Where you have code that says `.IN_SEQUENCE(seq_obj)`, you can see, right there, that something is done with the expectation, and that this something has to do with an object called `seq_obj`. This is a strong hint, and even better, if you don't know what it is, you can easily look up [`.IN_SEQUENCE()`](https://github.com/rollbear/trompeloeil/blob/master/docs/reference.md#IN_SEQUENCE) in the documentation and find out.

So, hidden dependencies, when code does different things depending on things that aren't immediately visible, are problematic. I have seen, and fixed, numerous tests that were wrong in exactly this respect, with exactly this functionality, because the person who made changes to an existing test, didn't see the invisible dependency, and did the wrong thing by accident, and the compiler didn't tell - it just produced code that did something other than expected.

**Comment by rcdailey** [comment]
You make very good arguments. Really if the trade off for less boilerplate / convenience is more error-prone test cases, it's definitely not worth it. Thank you for explaining. I will close.
