### ISSUE TITLE
Optional RTTI Support

### ISSUE THREAD

**Issue by leanderhendrikx** [rollbear/trompeloeil#122]
Hi,

I noticed that RTTI is only required in one place: `deathwatched<T>`. It seems a bit unfortunate to require RTTI for one debug statement. Is it possible to make that line only compile when compiled with RTTI?

It would make the framework useable for a lot more people.

**Comment by rollbear** [comment]
Thank you for this suggestion.

Since RTTI is not needed for the functionality, per se, but for printing more useful messages when your tests fail, it should be relatively easy to fix (but in that case with less informative error messages.)

I know how to test for RTTI support with gcc and clang, but what's the status with MSVC? I'm a bit lost there.

**Comment by leanderhendrikx** [comment]
`_CPPRTTI` should be defined when /GR is used.

https://docs.microsoft.com/en-us/cpp/build/reference/gr-enable-run-time-type-information?view=vs-2017

**Comment by rollbear** [comment]
Thanks. Experimental support is now implemented on the `develop` branch. Please have a go at it.

**Comment by leanderhendrikx** [comment]
Verified on clang 7.0.0, clang 8.0.0, GCC 8.3 and MSVC v19.16. Thanks!

**Comment by rollbear** [comment]
Thanks. I'm leaving the issue open until it has landed in a tagged release.

**Comment by rollbear** [comment]
This is included in the stable v34 release, so closing now.
