### ISSUE TITLE
Is it possible to mock methods returning std::pair?

### ISSUE THREAD

**Issue by piponazo** [rollbear/trompeloeil#126]
I stumbled upon a compilation error when trying to mock a method returning `std::pair`:

```cpp
#include <catch2/catch.hpp>
#include <trompeloeil.hpp>

#include <utility>
#include <vector>

class TestPair
{
public:
    virtual ~TestPair() {}
    virtual int method1(int, int) = 0;
    virtual std::vector<int> method2(int, int) = 0;
    virtual std::pair<int, int> method3(double) = 0;
};

class TestPairMock : public TestPair
{
public:
    MAKE_MOCK2(method1, int(int, int), override);
    MAKE_MOCK2(method2, std::vector<int>(int, int), override);
    MAKE_MOCK1(method3, std::pair<int, int>(double), override);
};
```

The compilation error has dozens lines of code ... and it ends up indicating:

```
/home/luis/programming/trompeloeilExample/tests/testBar.cpp: In function ‘void ____C_A_T_C_H____T_E_S_T____0()’:
/home/luis/programming/trompeloeilExample/tests/testBar.cpp:32:18: error: cannot declare variable ‘mock’ to be of abstract type ‘TestPairMock’
     TestPairMock mock;
                  ^~~~
/home/luis/programming/trompeloeilExample/tests/testBar.cpp:16:7: note:   because the following virtual functions are pure within ‘TestPairMock’:
 class TestPairMock : public TestPair
       ^~~~~~~~~~~~
/home/luis/programming/trompeloeilExample/tests/testBar.cpp:13:33: note: 	virtual std::pair<int, int> TestPair::method3(double)
     virtual std::pair<int, int> method3(double) = 0;

```

Is it a bug in the library or am I doing something wrong? 

Some details about my platform and configuration:
System: Ubuntu 18.04
Compiler: Gcc 7.3
Compiling with -std=c++14

**Comment by rollbear** [comment]
It's a problem with the preprocessor. It doesn't work well with templates. It thinks that the parameters to `MAKE_MOCK2()` are `method3`, `std::pair<int`, followed by `int>(double)` and `override`.

The way around this is to create an alias:

```Cpp
using pair_int_int = std::pair<int,int>;
MAKE_MOCK1(method3, pair_int_int(double), override);
```

Not pretty, I agree, but I don't see any way around it as the language works today.

See: https://gcc.godbolt.org/z/Gl0jlF

Maybe this should go into the FAQ.

In your case, since you're mocking an interface, you can also use `mock_interface` and `IMPLEMENT_MOCKn`. See https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#-creating-mock-classes

https://gcc.godbolt.org/z/auudMH

**Comment by piponazo** [comment]
Thanks for the prompt answer! Both tricks work for me, and in fact I learned about `mock_interface` which is much more interesting for me :smile_cat: .

Indeed it would be good to point out this issue somewhere in the documentation or FAQ. 

Feel free to close this issue now or when you document the tips.

**Comment by rollbear** [comment]
FAQ updated on branch `master`. Please have a look, and close this issue if you're happy with it, otherwise tell me what's missing (or wrong.)
