### ISSUE TITLE
Using ALLOW_CALL from within a scope

### ISSUE THREAD

**Issue by bitwizeshift** [rollbear/trompeloeil#15]
One observation I've had about this library is that the `ALLOW_CALL` macro doesn't properly function in instances where `ALLOW_CALL` is invoked from within a deeper scope than the function invocation.

In most cases this wouldn't be a problem, however this prevents things like implementing the [builder pattern](https://www.kenneth-truyers.net/2013/07/15/flexible-and-expressive-unit-tests-with-the-builder-pattern/) for classes that contain interfaces, since the `ALLOW_CALL` can't be within one of the given scopes (preventing building with mocks). 

### Example

A contrived example of this problem is below:
**MyClass**:
```c++
class MyClass
{
public:
    MyClass(std::shared_ptr<Type> type) noexcept : type_(type){}

    std::shared_ptr<Type> getType(){ return type_; }
private:
    std::shared_ptr<Type> type_;
};
```

**Type**:
```c++
struct Something{};

class Type
{
public:
    virtual ~Type() = default;

    virtual Something& getSomething() = 0;
};
```
**TypeMock**:
```c++
class TypeMock final : public Type
{
public:
    MAKE_MOCK0(getSomething,Something&(),override);
};
```

**Builder**:
```c++
class MyClassBuilder final
{
public:
    MyClassBuilder ()
        : typeMock_(std::make_shared<TypeMock>())
    {
    }

    std::shared_ptr<MyClass> build()
    {
        return std::make_shared<MyClass>(typeMock_);
    }

    MyClassBuilder& withType(std::shared_ptr<Something> something)
    {
        ALLOW_CALL(*typeMock_, getSomething()).RETURN(*something);
        // This scope is the problem
        return *this;
    }

private:
    std::shared_ptr<TypeMock> typeMock_;
};
```

**Failure:**
```c++
    auto something = std::make_shared<Something>();
    auto sut = MyClassBuilder()
                .withType(something)
                .build();

    auto something = sut->getType()->getSomething(); // fails here
```

This fails with the message (from clang):

 > libc++abi.dylib: terminating with uncaught exception of type trompeloeil::expectation_violation:
> No match for call of getSomething with signature Something&() with.

### Cause

Looking into this, I've found that `ALLOW_CALL` expands into a temporary local variable that allows for the invocation. In the above example, this temporary destructs at the end of `withType` which is what causes the failure with calling `sut->getType()->getSomething()`. This seemed to be fixed by changing `ALLOW_CALL` into `static ALLOW_CALL` -- however I feel that this is abusing the underlying implementation of your library.

Do you have any plans to support such a use-case, or perhaps have a suggestion for how this can be achieved with the current design without requiring replication of `ALLOW_CALL`s? What are the implications of changing the temporary variable to `static` -- are there any known side-effects?

**Comment by rollbear** [comment]
I think I need to sleep on this to be certain, but my gut reaction is that I've failed in the documentation rather than the implementation.

`ALLOW_CALL(...)` sets up an expectation for what is allowed to happen until the end of the scope. As you've noticed, by the time you want the result, that expectation has long since expired and is no good for you (indeed, it expires already at the end of the function, which is way before it does any good at all.)

If I've understood the situation correctly, you need to keep the expectation alive outside the local scope of the `withType()` function. The way to do this is to use `NAMED_ALLOW_CALL(...)`, which creates a `std::unique_ptr<trompeloeil::expectation>`, which you then need to store until it is no longer of interest.

A possible solution, then, would be:

```Cpp
class MyClassBuilder final
{
public:
    MyClassBuilder ()
        : typeMock_(std::make_shared<TypeMock>())
    {
    }

    std::shared_ptr<MyClass> build()
    {
        return std::make_shared<MyClass>(typeMock_);
    }

    MyClassBuilder& withType(std::shared_ptr<Something> something)
    {
        somethingGetter_ = NAMED_ALLOW_CALL(*typeMock_, getSomething()).RETURN(*something);
        // keep the expectation alive!
        return *this;
    }

private:
    std::shared_ptr<TypeMock> typeMock_;
    std::unique_ptr<trompeloeil::expectation> somethingGetter_; // where to keep the getSomething() expectation
};
```

Of course, if you need more than one, you may want `somethingGetter_` to rather be a `list<>` or `vector<>` of `std::unique_ptr<trompeloeil::expectation>`, which you add to.

Does this make sense, or have I misunderstood the problem?

**Comment by bitwizeshift** [comment]
@rollbear 
That makes complete sense -- and upon double-checking it appears I missed that concept in the documentation. It appears this was an RTFM problem on my part - my bad!

Sorry for taking your time! 
Keep up the good work, and thanks for an excellent library :smile:

**Comment by rollbear** [comment]
Glad to help @bitwizeshift , and I like users that report things, so don't worry, and don't hesitate to report another one, no matter how trivial.
