### ISSUE TITLE
Unclear how to mock a noexcept function

### ISSUE THREAD

**Issue by RedDwarf69** [rollbear/trompeloeil#151]
So I have an interface where a function is noexcept. I try to mock it with `IMPLEMENT_MOCK1(<function>);` and the compiler complains with `looser throw specifier`.
I have looked at https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md but I didn't see anything about what to do in such a case. Does the mock function need to throw exceptions?

**Comment by rollbear** [comment]
It's *really* complicated. If a function that has a return type is called without any matching expectation, what should happen? It cannot return, because what would it return? You could say return a default constructed value, but what about types that aren't default constructible (besides that it's a really bad idea.)

I can really only think of 2 alternative ways to handle those situations. Terminate or `longjmp`. Both are problematic.

One could make a special case for `void` functions, but I think that's problematic too.

So, unfortunately I don't really have a solution for you.

**Comment by rollbear** [comment]
Or, to be more precise, it's easy to handle, just not in a nice way. Just as you can add an `override` to a mock function, you can add `noexcept`.

https://godbolt.org/z/TCSM2R

However, be prepared that if your reporter throws, it will mean termination of the program instead of a nice clean message and continue with the next test.

**Comment by RedDwarf69** [comment]
Probably an entry in the FAQ with this info would be useful.
But other than that I'm fine with the available options and you can close the issue, it certainly looks problematic.

**Comment by rollbear** [comment]
Added to FAQ, and mention `noexcept` in the refman for **`MAKE_MOCKn`** and **`MAKE_CONST_MOCKn`**.
