### ISSUE TITLE
Trouble with mocking multiple return values

### ISSUE THREAD

**Issue by greg9702** [rollbear/trompeloeil#184]
Im struggling with mocking a random generator function. I have to test a function that calls the random generator function multiple times. This function has the same signature in every call. Is it possible to achive different return values for each call?

**Comment by AndrewPaxie** [comment]
Thanks for reopening this.

**Comment by rollbear** [comment]
I am struggling a bit with understanding what the problem is.

One thing you can do, is to have the mock return something from a predefined function. Like:

```C++
class generator
{
public:
    MAKE_MOCK0(random, int());
};

TEST(...)
{
    int not_so_random_maybe = 0;
    generator gen;
    ALLOW_CALL(gen, random())
        .LR_RETURN(not_so_random_maybe++);

    function_under_test(gen); // will get incremented numbers from 0 for each call to gen.random().
}
```

You probably want a better function that postincrement of an integer.

Another option is, of course, to not use a mock, but to hand write the test double that you need for the occasion.
