### ISSUE TITLE
Is it possible to mock singleton class member functions?

### ISSUE THREAD

**Issue by IvanRibakov** [rollbear/trompeloeil#196]
I guess to be able to mock singletons I would ultimately need to be able to mock static member functions. Is it possible with trompeloeil?

**Comment by rollbear** [comment]
Absolutely, but indirectly. Have your static functions call members on an object. Place expectations on that object. For example:

```Cpp
struct mock_type {
    MAKE_MOCK1(func, void(int));
};

mock_type singleton_obj;

struct singleton {
    static void func(int i) { singleton_obj.func(i); }
}
```

```Cpp
testfunc
{
    REQUIRE_CALL(singleton_obj, func(3));
    
    // whatever that causes the singleton to be called.
}
```

Unlike many other mocking frameworks, expectations placed on the object are controlled by the test code and are not owned by the mock object, so you would have to make a non-trivial effort in order to "leak" expectations between tests.

**Comment by IvanRibakov** [comment]
@rollbear thank you for a quick response. I'm just getting started/evaluating trompeloeil so I would appreciate if you could elaborate your example above based on the sample code below. In particular, I'm not quite sure what is the role of `struct mock_type` and `struct singleton` how are they related to a singleton class/object.

```
# my_singleton.hpp

class MySingleton {

  public:
    static MySingleton &getInstance();
    int doSomething();

  private:
    explicit MySingleton();
    static MySingleton *m_instance;
};

----------------------------------------------
# my_worker.cpp

#include my_singleton.hpp

...
int MyWorker::doWork() {
    ...
    MySingleton singleton = MySingleton::getInstance();
    if (singleton.doSomething() < 0) {
        return -1;
    }
    ...
    return 1;
}
```

Based on the above structure, how could I mock `singleton.doSomething()` when unit-testing `doWork()` method?

**Comment by rollbear** [comment]
Thanks for your patience with my late response.

There are so many ways to model this. Which one is preferable is completely up to you. The only thing that is necessary is that you find *a* way to ensure that the call to your singleton ends up calling a function on a mock object that you can reach from the test code. I showed one example above. Another is that you completely replace `my_singleton.hpp` in tests, by means of the build system, so that you include a mock implementation instead. A third is that you make the `doSomething` function virtual, and allow test code to replace the singleton instance with a mock implementation. E.g.
```Cpp
class MySingleton {

  public:
    static MySingleton &getInstance();
    virtual int doSomething();

   static void set_instance_for_test(MySingleton* p) { m_instance = p; }
  private:
    explicit MySingleton();
    static MySingleton *m_instance;
};
```

```Cpp
class test_singleton : public MySingleton
{
public:
    MAKE_MOCK0(doSomething, int(void), override);
};

TEST(...)
{
    test_singleton s;
    MySingleton::set_test_instance(&s);

    ...
}
