### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by Viatorus** [rollbear/trompeloeil#213]
Hello, when do you plan to make a new release? :)

**Comment by rollbear** [comment]
Hopefully soon, but I want to see if I can fix #204. It's tricky, though. I fear I need a remodeling of how sequences are implemented.

**Comment by coffee-lord** [comment]
@rollbear Thank you and thanks to all the contributors for such a great framework!

Since the library seems pretty mature, have you considered adopting [Semantic Versioning](https://semver.org/)? The current `vN` scheme is pretty straightforward but I think the users would benefit from a more conventional versioning in the long run (easier to spot major API changes, users can specify version ranges and whatnot).

Just my 2 cents :wink: Cheers!

**Comment by rollbear** [comment]
@coffee-lord unrelated to the question of when to make a new release, but to answer your question, I have indeed considered semver, several times, and concluded that it's not a good idea. It's generally not a good idea because it's based on a false premise that there are changes that do not break existing practice. See ["Hyrum's Law"](https://www.hyrumslaw.com). Concrete and current: Issue 204, my old nemesis, (mentioned just above) may maybe, hopefully, be fixed. There will be existing working code that will break because of the fix. Guaranteed. Should I step a major?

Assuming we can ignore the above, however, it's still not a good idea.

As you mention, the library is very stable. In fact, it's so stable that the only changes in a very long time are bug fixes, so new releases wound only be patch level changes. There *may* be additions that perhaps could be represented by an increment of the minor version. However, I will not ever go back and fix a bug in an old minor version, so it's meaningless.

Remaining is the possible major version. Should I decide to make a deliberate API breaking change (like addressing a few fundamental design decisions that in hindsight weren't great, or go full C++-future with introspection and metaclasses) I'd prefer to release it under a new name. It'd be a very different library.

As for when, you can help by torturing the [`sequenced_allow_call`](https://github.com/rollbear/trompeloeil/tree/sequenced_allow_call) branch and report any problems to issue #204.

**Comment by coffee-lord** [comment]
> As you mention, the library is very stable. In fact, it's so stable that the only changes in a very long time are bug fixes, so new releases wound only be patch level changes. There may be additions that perhaps could be represented by an increment of the minor version.

If the current version were `1.0.38` what you just said would've been encoded in the version string itself :wink:

I understand what you mean though. However I still think that "every change is a breaking change because of Hyrum's Law" attitude is not helpful. While the version string has absolutely no bearing on the software itself, it does matter when it comes to maintenance, packaging and general user-friendliness. Going from `1.0` to `2.0` communicates that something big has changed and the user is advised to thoroughly study the changelog/documentation before considering upgrading, going from `1.0` to `1.1` tells the user that there's probably some minor fix or addition of sorts but the existing code should (hopefully) still work as-is. Going from `v38` to `v39` tells the user... well nothing, really. Unless the user is familiar with your library's particular versioning scheme.

Is `v38` a production ready version? Should I wait until `v40` before upgrading? Can I blindly switch to `v39` or should I research what's changed first? If I have several projects, one requires `v39` and the other `v38` can they both use `v39`? Granted, you've already answered all of these questions and your library works just as well whether it's `v39` or `1.2.42` but as someone who periodically checks dependencies for new releases it would make my life a smidge easier if everyone at least tried to conform to a common versioning scheme.

I understand that sometimes it might not be obvious when the software should transition from `1.0` to `1.1` or `2.0` but if you factor in the significance of the change for the end user and use your best judgement, usually you can come up with a version number that makes the most sense.

I'm sorry if I come off as arrogant, I do not mean to be disrespectful. Just sharing my opinion on the matter :stuck_out_tongue:

**Comment by rollbear** [comment]
Just tagged v39

**Comment by Viatorus** [comment]
Great! Thank you. :)
