### ISSUE TITLE
Different exception raised, depending on if running with or without Catch

### ISSUE THREAD

**Issue by jamespharvey20** [rollbear/trompeloeil#24]
I've found a situation where trompeloeil raises a different exception, when otherwise identical code is ran with or without catch.

This is of course a much reduced scenario.  I run into this often, and resort to commenting out expected calls that would succeed to find the "hidden" unexpected call.  Lots of guessing and re-compiling.  Been meaning to ask about this for a while.

**withoutCatch.cpp**

```
#include <trompeloeil.hpp>
using namespace trompeloeil;

class mock {
public:
   MAKE_MOCK0(a, void());
   MAKE_MOCK0(b, void());
};

int main() {
   mock x;
   REQUIRE_CALL(x, a());
   x.a();
   x.b();
}
```
As I'd expect, this gives an trompeloeil::expectation_violation with: `No match for call of b with signature void() with.`

As I'd expect, switching the positions of the calls to `x.a()` and `x.b()` gives the same exception.

**withCatch.cpp**
```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include <trompeloeil.hpp>
using namespace trompeloeil;

class mock {
public:
   MAKE_MOCK0(a, void());
   MAKE_MOCK0(b, void());
};

TEST_CASE("") {
   mock x;
   REQUIRE_CALL(x, a());
   x.a();
   x.b();
}
```
As I'd expect, this gives the same exception.

However, the (to me) unexpected behavior happens when switching the positions of the calls to `x.a()` and `x.b()`.  Meaning, when the unexpected call happens so the test aborts before the expected call happens.  This gives a different exception: `Unfulfilled expectation:\nExpected x.a() to be called once, actually never called`.

Why does calling an unexpected function within catch cause the exception to be about the unfulfilled expected call, when without catch the exception is about the unexpected call?

I'd much rather see the exception about the unexpected call, since the expected call is only unfulfilled because execution stops because of it.

Can I use catch and have the behavior I want?

**Comment by rollbear** [comment]
If I modify your `main()` to enclose your code in a `try`/`catch` block like:

```Cpp
int main()
{
  try {
    mock x;
    REQUIRE_CALL(x, a());
    x.b();
    x.a();
  }
  catch (std::exception& e)
  {
    std::cout << e.what() << '\n';
  }
}
```

I get the same error as you see in Catch.

The reason is that without the `try`/`catch` it is known that the program will terminate, so it terminates immediately when throwing the "Unexpected call" exception. With the `try`/`catch` in place, it actually throws, which causes stack rollback and destruction of the (hidden) expectation object for the call to `x.a()`, which in turns throws because it is not fulfilled. That throw during rollback is mandated by the standard to terminate, so it does, with that message.

The solution can be found in the documentation. Add a reporter adapter for Trompeloeil to Catch!
You can find two alternatives [here](https://github.com/rollbear/trompeloeil/blob/master/docs/CookBook.md#adapt_catch)

**Comment by rollbear** [comment]
Have you been able to move on, or is this still an unsolved problem for you?

**Comment by jamespharvey20** [comment]
Sorry, yes, you nailed it.  Thanks!
