### ISSUE TITLE
CMake version required not correct

### ISSUE THREAD

**Issue by Zara-ber** [rollbear/trompeloeil#310]
Hi
In (root)CMakeLists, the CM<KE version required is 3.14, but in test/CMakeLists.txt the version rage to locate Catch is 2..<3, a feature that works only from CMake version 3.19 onwards.
Pleasde fix it in first,  or make it explicit in second, whihever you think is the better solutiion.

Thanks!

**Comment by rollbear** [comment]
Good catch. Thank you! Will fix.

**Comment by rollbear** [comment]
Please check out branch [cmake_version](https://github.com/rollbear/trompeloeil/tree/cmake_version) and see what you think.

I've changed how you build, so that you need to be explicit about building the tests, by adding `-DTROMPELOEIL_BUILD_TESTS=yes` to your CMake command line. CMakeLists.txt for the tests explicitly require version 3.19. I've updated the README.

**Comment by Zara-ber** [comment]
Hi,
Now it fails (for me) correctly. Now I will get the newest version of cmake installed and continue.
Thanks a lot

**Comment by rollbear** [comment]
Excellent. I've merged this to main now. Leaving the issue open until a release has been tagged.

**Comment by rollbear** [comment]
Tagged v46 so closing now. Thanks for reporting and testing.
