### ISSUE TITLE
Trompeloeil is not thread-safe

### ISSUE THREAD

**Issue by SimonKagstrom** [rollbear/trompeloeil#8]
I have a set of tests written for a threaded program (i.e., not unit tests). I use trompeloeil to mock certain classes, but the program runs with multiple threads.

In the test cases, I get strange crashes, which I believe (or rather, have a vague feeling) are due to non-thread safety in trompeloeil. Am I correct in assuming trompeloeil is not thread safe? Would you consider making it thread-safe?

**Comment by rollbear** [comment]
This assumption is indeed correct.

For the moment I have no thoughts about making it thread safe, but let's keep this issue open for now.

**Comment by rollbear** [comment]
I just created a branch 'threadsafe'. For the moment it's very rudimentary, but I think this can become good.

I have not done any real threading testing with this, so all bets are off, but please give it a shot.

For the moment, it is only calls to mock functions that are protected between each other. Violation reporting is currently not protected by any lock, so for the moment it's only correct programs that will work.

There is one recursive_mutex per mocked function per object, so lock contention should be low, but if matching expectations calls other mocked functions, it is easy to deadlock. Other locking principles may be better. A big central trompeloeil-recursive-mutex would increase contention, but eliminate the risk for deadlock.

It is only calls to mock functions that are protected. Do not allow expectations to come and go while several threads operate. This too can be protected, without much difficulty, but with some work.

**Comment by rollbear** [comment]
Improved now. There is now a global trompeloeil recursive mutex. This is perhaps a step down, since it increases contention for that single mutex, but on the other hand the risk for dead lock is removed, and now also the expectations can come and go in competing threads.

What's not protected now are:
* expectations vis-a-vis destruction of mock objects. Don't go there. Ensure that the object is alive during the entire creation of an expectation. Destruction is OK.
* **`REQUIRE_DESTRUCTION`** and **`NAMED_REQUIRE_DESTRUCTION`** are not protected.

The global mutex also ensures that reporting of violations is protected.

The lock can be obtained with `auto lock = trompeloeil::get_lock();` The lock is `std::unique_lock<std::recursive_mutex>`, but please use `auto` if you need the lock, in case there is a reason to change it.

**Comment by rollbear** [comment]
Fixed in v13. Closing.

**Comment by SimonKagstrom** [comment]
Great, thanks!
