### ISSUE TITLE
check_errors.sh test fails on clang without failing the CI build

### ISSUE THREAD

**Issue by rollbear** [rollbear/trompeloeil#95]
The travis-ci builds run the script `check_errors.sh`, to ensure that intended compilation errors are reported correctly. Since some time ago these tests fail on clang++, but the failures do not fail the CI build.

**Comment by AndrewPaxie** [comment]
I have looked a little further into these failure reports, starting
with the last build of `master` in Travis, [build 501](
  https://travis-ci.org/rollbear/trompeloeil/builds/403136675
).

Results for Clang compiles,

```text
clang++-3.7           - All checks pass
clang++-3.8           - All checks pass
clang++-3.9           - All checks pass
clang++-4.0           - All checks FAIL

clang++-5.0           - All checks FAIL, except
                          expectation_with_unknown_func_name.cpp

clang++-6.0           - All checks pass
```

For completeness, I examined the logs of the g\+\+ builds

```text
g++-4.8 -std=c++11    - All checks pass, except these four tests
                          return_value_to_ref.cpp
                          return_wrong_pointer_constness.cpp
                          return_wrong_reference_constness.cpp
                          return_wrong_type_first.cpp
                        These are expected failures.

g++-4.9               - All checks FAIL, except
                          deathwatched_with_nonvirtual_destructor.cpp
                          expectation_with_wrong_cardinality.cpp

g++-5.0               - All checks FAIL, except
                          deathwatched_with_nonvirtual_destructor.cpp
                          expectation_with_wrong_cardinality.cpp

g++-6.0               - All checks pass
g++-7.0               - All checks pass
g++-8.0               - All checks pass
```

And here are the result from the logs of the Xcode builds,

```text
xcode9 C++            - All checks FAIL, except
                          expectation_with_unknown_func_name.cpp

xcode8 C++            - All checks FAIL, except
                          expectation_with_unknown_func_name.cpp

xcode7.3 C++          - All checks FAIL, except
                          expectation_with_unknown_func_name.cpp
```

I run `./check_errors.sh` locally for a broad range of
build configurations and do not receive any unexpected failures.
I cannot run any of the Xcode builds locally however.

To be sure, there is missing code in the `.travis.yml` that doesn't
check `FAILURES` for non-zero return code for non-C\+\+11 builds.
But that is code we should add **last**, and understand the
difficulties Travis is having running this script, or parsing
the result of the compile.

A look inside `check_errors.sh` shows a number of possible
points of failure:

- Perhaps the setting of `CXXFLAGS` to a default value is being mangled.
- `sed` might not run, or not find the matching string in `$f`.
- The compiler might not run, or not output error messages
  in a format that matches according to `${RE}`.
- `egrep` might not run.

A first step may be to enable output of the environment variables
that invoke the compiler, `CXX`, `CXXFLAGS`, `CPPFLAGS`.
We could also consider printing `${RE}`.

We might also want to break down the expression evaluating the
result of `egrep`.

The expression computing `FAILURES` could be changed to
`FAILURES=$((FAILURES+1))` since the return code of `false` is
always `1`.  This avoids having to reason about the overall
return code of the previous line.

**Comment by rollbear** [comment]
I agree. I wonder if it might be a good idea to create a topic branch for this, since I assume there'll be a bunch of exploratory commits, while trying to figure out what's happening? We can then squash the merge to contain only the relevant fixes, once we're done.

**Comment by AndrewPaxie** [comment]
A topic branch sounds ideal, given our history of many Travis build commits with one character
changes, or so it seemed to me the last time I ventured into this area.  If you don't mind,
I would like to take the lead on resolving this issue.  If OK then look for a branch called
`check_errors` in the near future.

**Comment by rollbear** [comment]
Absolutely, go ahead.

One observation I did in the `check_errors.sh` script is that it sets `CXXFLAGS` to `-std=c++14` iff `CXXFLAGS` is not already set. So if it is set to something in the failing runs, that might explain it. I haven't dug into this, though, so it may be a red herring.

**Comment by AndrewPaxie** [comment]
You intuition was sound.  The line to default `CXXFLAGS` was missing a colon.
Don't know what the shell thought of that except to behave in a random fashion.

Failures from `check_errors.sh` are now checked in the Travis script.
Not the best code, but functional.

**Comment by rollbear** [comment]
Since this bug did not affect users of the library, only use developing it, it's safe to close already. Thanks again.
