### ISSUE TITLE
Trompeloeil for Microsoft vcpkg

### ISSUE THREAD

**Issue by denvercoder21** [rollbear/trompeloeil#99]
I'd like to be able to use Trompeloeil with Microsoft's [vcpkg](https://github.com/Microsoft/vcpkg) so it's shown and installable when searching/installing with vcpkg like so:
```
./vcpkg search trompeloeil
./vcpkg install trompeloeil
```

**Comment by denvercoder21** [comment]
I could give it a shot following [this guide](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/packaging-zlib.md). However, I'm don't know how to create a suitable .zip of Trompeloeil.

**Comment by rollbear** [comment]
I have no experience at all with vcpkg, and don't know at all what's expected, hence the plea for help.

You can maybe compare with the conan package, which really only contains the header file.

**Comment by rollbear** [comment]
Is there an organisation for open source vcpkg:ing, like [bincrafters](https://bincrafters.github.io) for Conan?
I'd prefer it if it didn't become part of my release process to make and upload packages.

**Comment by ras0219-msft** [comment]
@rollbear Vcpkg as a whole operates similarly to bincrafters for maintenance and quality, however someone still has to do the initial packaging for the library and make a PR (all part of the short guide that @denvercoder21 linked).

As for release process: since you're on GitHub, once the initial PR is accepted we can automatically update the port whenever a new tag is released as long as there aren't any structural changes (such as new dependencies). Additionally, vcpkg is entirely from source, so there is no need to build a billion flavors to push a new package; it's as simple as updating the git reference and a SHA512 hash.
